# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def common_pods
    pod 'Firebase/Core'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'KeychainAccess'
    pod 'NVActivityIndicatorView'
#    pod 'RxSwift'
    pod 'IQKeyboardManager'
    pod 'Shimmer'
    pod 'ISO8601', git: 'https://github.com/onmyway133/ISO8601'
end

target 'ApproachCleanArchitecture' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    common_pods
    
    # Pods for ApproachCleanArchitecture
    
    target 'ApproachCleanArchitectureTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'ApproachCleanArchitectureUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
